### ISSUE TITLE
Training Procedure unclear

### ISSUE THREAD

**Issue by sebk26** [MostafaAghaei/Prediction-of-the-roughness-equivalent-sandgrain-height#3]
Hello Mr. Ahgaei,

thank you so much for your work. I liked the paper very much!

I have two questions regarding the training procedure in `./2/trainGPR.ipynb`:
```python
while by4<10000.:
            by4=by4+1
            kernel1 = RBF(10, (1e-3, 1e2))
            kernel2 = RBF(5, (1e-3, 1e2))
            kernel3 = RationalQuadratic(length_scale=1.0, alpha=0.1)
            kernel4 = Matern(length_scale=1.0, length_scale_bounds=(1e-05, 100000.0), nu=4.5)
            kernel5 = ExpSineSquared(length_scale=2.0, 
                        periodicity=3.0, 
                        length_scale_bounds=(1e-05, 100000.0), 
                        periodicity_bounds=(1e-05, 100000.0))
            kernel6 = DotProduct()
            
            gpr = GaussianProcessRegressor(kernel=kernel1, n_restarts_optimizer=1000)
            gpr = GaussianProcessRegressor(kernel=kernel3, n_restarts_optimizer=1000,alpha=.1)
            
            
            
            print("by4: %f" % by4)

            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
            gpr.fit(X_train, y_train)
```

1. In the end you only train kernel3, right? So the rest is just for trying out different kernels.
2. The only thing that varies inside the `while`-loop is the `train_test_split` or am I missing something? So here you do 10000 samplings of the dataset to get a set of training and testsamples to which the selected kernel fits best.
Did you opensource the part to which you refer in your paper with *"The preset parameters [...] were also tuned with the available data by running the GPR compiler approximately 8000 times."* and if yes, i might need a pointer to where in the code.

**Comment by MostafaAghaei** [comment]
Hello, 

The actual loop contains different parameters, e.g. kernels and their options, n_restart_optimizer, etc.
 To make the code concise yet exhaustive, it was cleaned up here and only the final result was included.
